"""phone

Revision ID: 3f6a31f94ccf
Revises: e999178ea78b
Create Date: 2022-07-22 15:03:21.716580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f6a31f94ccf'
down_revision = 'e999178ea78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone1', sa.String(length=20), nullable=True))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone1')
    # ### end Alembic commands ###
