"""modification2

Revision ID: 66fe9dcc8df6
Revises: b6d0e6f16ff9
Create Date: 2022-07-06 13:39:54.814322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66fe9dcc8df6'
down_revision = 'b6d0e6f16ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('date_uploaded', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'date_uploaded')
    # ### end Alembic commands ###
