"""add picture model and add banner image and profile pic

Revision ID: b34fac3a99ab
Revises: cda1d5a7bd01
Create Date: 2022-07-06 12:59:09.615375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b34fac3a99ab'
down_revision = 'cda1d5a7bd01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('res_type', sa.String(length=20), nullable=False),
    sa.Column('res_status', sa.String(length=20), nullable=False),
    sa.Column('res_description', sa.Text(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('img_uploaded', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('banner_img', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    op.drop_column('users', 'data_added')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data_added', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'date_added')
    op.drop_column('posts', 'banner_img')
    op.drop_table('photos')
    # ### end Alembic commands ###
