"""add comment model and some modification

Revision ID: cda1d5a7bd01
Revises: c212912ad556
Create Date: 2022-07-04 11:11:29.553230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cda1d5a7bd01'
down_revision = 'c212912ad556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('date_pub', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('status', sa.String(length=10), nullable=False))
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    op.alter_column('posts', 'slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('posts', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'posts', ['title'])
    op.create_unique_constraint(None, 'posts', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    op.alter_column('posts', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('posts', 'slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('posts', 'views')
    op.drop_column('posts', 'status')
    op.drop_column('posts', 'comment_count')
    op.drop_table('comments')
    # ### end Alembic commands ###
