"""remove photo table

Revision ID: e999178ea78b
Revises: cdf9cf6e368f
Create Date: 2022-07-22 14:49:04.131352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e999178ea78b'
down_revision = 'cdf9cf6e368f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('res_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('res_status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('res_description', mysql.TEXT(), nullable=False),
    sa.Column('uploader_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_uploaded', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('date_uploaded', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name='photos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
